"""updtae user table 

Revision ID: 6d88ca87e9f2
Revises: d242662cd127
Create Date: 2025-08-19 12:24:45.667595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d88ca87e9f2'
down_revision: Union[str, Sequence[str], None] = 'd242662cd127'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_subscription_id_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'subscription_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscription_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('users_subscription_id_fkey'), 'users', 'subscriptions', ['subscription_id'], ['id'])
    # ### end Alembic commands ###
