"""fix foreign keys in Payment model

Revision ID: b0b7fb995780
Revises: c96288759957
Create Date: 2025-08-19 12:08:02.433489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0b7fb995780'
down_revision: Union[str, Sequence[str], None] = 'c96288759957'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'CANCELLED', name='status'), nullable=False))
    op.add_column('users', sa.Column('user_type', sa.Enum('USER', 'ADMIN', name='usertype'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_type')
    op.drop_column('subscriptions', 'status')
    # ### end Alembic commands ###
