"""updtae user table 

Revision ID: d242662cd127
Revises: b0b7fb995780
Create Date: 2025-08-19 12:17:51.234205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd242662cd127'
down_revision: Union[str, Sequence[str], None] = 'b0b7fb995780'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscription_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'subscriptions', ['subscription_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'subscription_id')
    # ### end Alembic commands ###
