"""create users,subscriptions and plans table

Revision ID: f1271305f9b9
Revises: 
Create Date: 2025-08-08 13:36:48.924907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1271305f9b9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_title', sa.Enum('STANDARD', 'PRO', name='plantitle'), nullable=False),
    sa.Column('plan_period', sa.Enum('MONTHLY', 'YEARLY', name='planperiod'), nullable=False),
    sa.Column('plan_amount', sa.Float(), nullable=False),
    sa.Column('free_trial_days', sa.Integer(), nullable=False),
    sa.Column('pdf_upload_limit', sa.Integer(), nullable=True),
    sa.Column('question_limit', sa.Integer(), nullable=True),
    sa.Column('ai_response_type', sa.Enum('BASIC', 'ADVANCED', name='airesponsetype'), nullable=False),
    sa.Column('chat_history', sa.Boolean(), nullable=False),
    sa.Column('priority_support', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plans')
    # ### end Alembic commands ###
