name: CI/CD - FastAPI & Next.js

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend:
    name: Backend (FastAPI)
    runs-on: ubuntu-latest
    env:
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Lint and Type Check (optional)
        run: |
          echo "Add flake8 or mypy commands here if needed"

      - name: Run FastAPI server test
        run: |
          cd backend
          uvicorn app.main:app --host 127.0.0.1 --port 8000 &
          sleep 5
          curl -f http://127.0.0.1:8000 || exit 1

  frontend:
    name: Frontend (Next.js)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        working-directory: frontend/docuaipro
        run: npm install

      - name: Build Next.js App
        working-directory: frontend/docuaipro
        run: npm run build

      - name: Lint Check
        working-directory: frontend/docuaipro
        run: npm run lint
